services:
  reading-recorder-db:
    image: postgres:18
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: reading_recorder_user
      POSTGRES_PASSWORD: reading_recorder_pass
      POSTGRES_DB: reading_recorder
    volumes:
      - reading_recorder_vol:/var/lib/postgresql
volumes:
  reading_recorder_vol:
